# Generated by Django 3.1.3 on 2020-11-05 10:31

from django.db import migrations, models
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DasriForm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('readable_id', models.CharField(blank=True, db_index=True, max_length=30, unique=True, verbose_name='Identifiant lisible')),
                ('state', django_fsm.FSMField(choices=[('DRAFT', 'Brouillon'), ('CANCELED', 'Annulé'), ('WAITING_FOR_TAKE_OVER', "En attente d'enlèvement"), ('SENT', 'Envoyé'), ('RECEIVED', 'Reçu'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('PROCESSED', 'Traité')], default='DRAFT', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formulaire dasri',
                'verbose_name_plural': 'Formulaires dasri',
                'ordering': ('-created',),
            },
        ),
    ]
